### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by xidongdxi** [openpharma/RobinCar2#50]
Current imports list includes checkmate, numDeriv, MASS, prediction, sandwich, stats

checkmate further imports backports (>= 1.1.0), utils
prediction further imports utils, stats, data.table
sandwich further imports stats, utils, zoo

I am wondering about the necessity of having these dependencies, especially about the need of importing checkmate and prediction.

**Comment by clarkliming** [comment]
I can comment on the dependencies

1. `{checkmate}` I will recommend to keep. it is commonly used to check the arguments to build strong code. 
2. `{prediction}` we can remove. this package only builds the data from the fit (e.g. for lm, or glm) (also make it work if the variable is from the global environment). But we can remove this dependency as we can make strong assumptions/checks that all the variables are availabe in the dataset
3. `{sandwich}` I will recommend to keep because it include the vcovHC which is widely used.

**Comment by clarkliming** [comment]
of course we can use other checking package, but I do believe `{checkmakte}` is already very light-weighted (and also very efficient)

**Comment by xidongdxi** [comment]
Thank you Liming for the explanation. If we could try to drop prediction, I think it will be great.
